<?php
/**
 * Created by PhpStorm.
 * User: devop
 * Date: 30.12.15
 * Time: 13:33
 */

namespace giantbits\crelish\plugin\core;

use giantbits\crelish\components\CrelishBaseTypeProcessor;
use giantbits\crelish\components\CrelishCollectionInterface;

class ModularTypeProcessor extends CrelishBaseTypeProcessor implements CrelishCollectionInterface {

  public function init() {
    parent::init(); // TODO: Change the autogenerated stub
  }

  protected function processModularFile($file) {
    $rawContent = $this->loadFileContent($file);

    //$headers = $this->getMetaHeaders();
    $meta = $this->fileHandler->parseFileMeta($rawContent);

    $processedContent = $this->fileHandler->prepareFileContent($rawContent, $meta, TRUE);
    $processedContent = $this->fileHandler->parseFileContent($processedContent);

    $template = $this->selectTemplate($meta, $file);

    return $this->renderPartial($template, [
      'content' => $processedContent,
      'data' => $meta
    ]);
  }

}
