<?php
/**
 * Created by PhpStorm.
 * User: devop
 * Date: 29.11.15
 * Time: 17:19
 */

namespace giantbits\crelish\controllers;

use yii\base\Controller;
use crelish\components\CrelishFileDataProvider;

class AssetController extends Controller
{

  public $layout = 'crelish.twig';

  public function init()
  {
    parent::init(); // TODO: Change the autogenerated stub
  }

  public function actionIndex()
  {
    $modelProvider = new CrelishFileDataProvider('asset');

    return $this->render('index.twig', [
      'dataProvider' => $modelProvider->raw()
    ]);
  }

  public function actionUpload()
  {
    return;
  }
}
