<?php
/**
 * Created by PhpStorm.
 * User: devop
 * Date: 29.11.15
 * Time: 17:19
 */

namespace giantbits\crelish\controllers;

use giantbits\crelish\components\CrelishBaseController;
use yii\filters\AccessControl;

class DefaultController extends CrelishBaseController {

    public $layout = 'crelish.twig';

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['create', 'index', 'delete'],
                'rules' => [
                    [
                        'allow' => TRUE,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Override the setupHeaderBar method for default-specific components
     */
    protected function setupHeaderBar()
    {
        // Default left components for all actions
        $this->view->params['headerBarLeft'] = ['toggle-sidebar'];
        
        // Default right components (empty by default)
        $this->view->params['headerBarRight'] = [];
        
        // Set specific components based on action
        $action = $this->action ? $this->action->id : null;
        
        switch ($action) {
            case 'index':
                // For default index, just show the toggle sidebar
                break;
                
            default:
                // For other actions, just keep the defaults
                break;
        }
    }

    public function actionIndex() {
        return $this->render('index.twig');
    }
}
