<?php
/**
 * Created by PhpStorm.
 * User: devop
 * Date: 29.11.15
 * Time: 17:19
 */

namespace crelish\controllers;

use yii;
use giantbits\crelish\components\CrelishBaseController;

class FrontendController extends CrelishBaseController {

  public function init()
  {
    parent::init(); // TODO: Change the autogenerated stub

    Yii::$app->view->theme  = Yii::createObject([
      'class' => 'yii\base\Theme',
      'basePath' => '@app/themes/klangfarbe',
      'baseUrl' => '@web/themes/klangfarbe',
      'pathMap'=>[
        '@app/views' => '@app/themes/klangfarbe'
      ]
    ]);

    // Force theming from base app.
    $this->setViewPath('@app/views');
  }
}
