<?php
/**
 * Created by PhpStorm.
 * User: devop
 * Date: 03.01.16
 * Time: 13:48
 */

namespace crelish\components;


use yii\base\Component;

class CrelishContentCollection extends Component{

  public $collection;

  public function init() {
    parent::init(); // TODO: Change the autogenerated stub
  }


}
