<?php
namespace giantbits\crelish\widgets;

use giantbits\crelish\components\CrelishJsonDataProvider;
use yii\base\Widget;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

class JobFilter extends Widget
{
  public $dataProvider;
  public $category;

  public function init()
  {

    switch($this->category){
      case 'educational':
        $dp = "bachelor";
        break;
      case 'internship_provider':
        $dp = "internship_provider";
        break;
      case 'apprentice_provider':
        $dp = "apprentice_provider";
        break;
      default:
        $dp = "job";
    }

    $this->dataProvider = new CrelishJsonDataProvider($dp);

    parent::init(); // TODO: Change the autogenerated stub
  }

  public function run()
  {

    // Filter model.
    $filter = new \yii\base\DynamicModel(['company']);
    $filter->addRule(['company'], 'string', ['max' => 128]);
    if ($filter->load(\Yii::$app->request->post()) && $filter->validate()) {
      // do what you want
    }

    $out = '';

    // todo: Refactor.
    $unique_categories = array_unique(array_map(function ($elem) {
      return $elem['category'];
    }, $this->dataProvider->rawAll()));

    $unique_companies = array_unique(array_map(function ($elem) {
      return $elem['company']['title'];
    }, $this->dataProvider->rawAll()));

    $unique_countries = array_unique(array_map(function ($elem) {
      return $elem['company']['country']['title'];
    }, $this->dataProvider->rawAll()));

    $unique_branches = array_unique(array_map(function ($elem) {
      return $elem['branch'];
    }, $this->dataProvider->rawAll()));

    asort($unique_categories);
    asort($unique_companies);
    asort($unique_countries);
    asort($unique_branches);

    $unique_companies = $this->buildSelfArray($unique_companies);
    $unique_countries = $this->buildSelfArray($unique_countries);
    $unique_branches = $this->buildSelfArray($unique_branches);

    if($this->category == 'apprentice_provider' || $this->category == 'internship_provider') {
      $unique_categories = $this->buildSelfArray($unique_categories);
    }

    // Output.
    ob_start();

    echo Html::script('
      successCounter = 0;
    
      setFilterCategory = function( cat ) {
        $(".filter_category").val(cat); 
        $("#filter").submit();
      };
      
      $(document).on("ready pjax:success", function(e){
          $("html, body").animate({
              scrollTop: $(".events").offset().top - 120
          }, 0);
      });
    ');

    echo '<form action="' . Url::to(['/' . $_GET['pathRequested']]) . '" method="GET" data-pjax="" id="filter">';

    echo \yii\bootstrap\Html::hiddenInput('category', \Yii::$app->getRequest()->getQueryParam('category'), ['class' => 'filter_category']);
    echo \yii\bootstrap\Html::hiddenInput('page', \Yii::$app->getRequest()->getQueryParam('page'));

    if($this->category != 'internship_provider' && $this->category != 'apprentice_provider') {
      echo Html::beginTag('div', ['class' => 'form-group']);
      echo \yii\bootstrap\Html::label('Kategorie');
      echo Html::beginTag('ul', ['class' => 'nav nav-pills']);
      echo Html::tag('li', Html::a('Alle', '#', ['onClick' => 'setFilterCategory(0); return false;']), ['class' => (empty(\Yii::$app->getRequest()->getQueryParam('category'))) ? 'active' : '']);
      foreach ($unique_categories as $category) {
        if (\Yii::$app->getRequest()->getQueryParam('category') == $category) {
          $css = 'active';
        } else {
          $css = '';
        }
        echo Html::tag('li', Html::a($category, '#', ['onClick' => 'setFilterCategory("' . $category . '"); return false;']), ['class' => $css]);
      }
      echo Html::endTag('ul');
      echo Html::endTag('div');
    }

    echo Html::beginTag('div', ['class' => 'form-group']);
    echo \yii\bootstrap\Html::label($this->category == 'educational' ? 'Institut' : 'Firma');
    echo \yii\bootstrap\Html::dropDownList('company', \Yii::$app->getRequest()->getQueryParam('company'), $unique_companies, ['class' => 'selectize form-control']);
    //echo \yii\bootstrap\Html::textInput('company', \Yii::$app->getRequest()->getQueryParam('company'), ['id' => 'company-ahead', 'class' => 'form-control']);
    echo Html::endTag('div');

    echo Html::beginTag('div', ['class' => 'form-group']);
    echo \yii\bootstrap\Html::label('Land');
    echo \yii\bootstrap\Html::dropDownList('company|country|title', \Yii::$app->getRequest()->getQueryParam('company|country|title'), $unique_countries, ['class' => 'selectize form-control']);
    //echo \yii\bootstrap\Html::textInput('country', \Yii::$app->getRequest()->getQueryParam('country'), ['id' => 'country-ahead', 'class' => 'form-control']);
    echo Html::endTag('div');

    if($this->category == 'job') {
      echo Html::beginTag('div', ['class' => 'form-group']);
      echo \yii\bootstrap\Html::label('Branche');
      echo \yii\bootstrap\Html::dropDownList('branch', \Yii::$app->getRequest()->getQueryParam('branch'), $unique_branches, ['class' => 'selectize form-control']);
      //echo \yii\bootstrap\Html::textInput('country', \Yii::$app->getRequest()->getQueryParam('country'), ['id' => 'country-ahead', 'class' => 'form-control']);
      echo Html::endTag('div');
    }

    if($this->category == 'internship_provider' || $this->category == 'apprentice_provider') {
      echo Html::beginTag('div', ['class' => 'form-group']);
      echo \yii\bootstrap\Html::label('Kategorie');
      echo \yii\bootstrap\Html::dropDownList('category', \Yii::$app->getRequest()->getQueryParam('category'), $unique_categories, ['class' => 'selectize form-control']);
      //echo \yii\bootstrap\Html::textInput('country', \Yii::$app->getRequest()->getQueryParam('country'), ['id' => 'country-ahead', 'class' => 'form-control']);
      echo Html::endTag('div');
    }

    echo \yii\bootstrap\Html::submitButton("Filter anwenden", ['class' => 'btn btn-default']);

    echo "</form>";

    $out .= ob_get_clean();

    $js = <<<JS
    
      $(document).ready( function() {
        substringMatcher = function(strs) {
          return function findMatches(q, cb) {
            var matches, substringRegex;
        
            // an array that will be populated with substring matches
            matches = [];
        
            // regex used to determine if a string contains the substring `q`
            substrRegex = new RegExp(q, 'i');
        
            // iterate through the pool of strings and for any string that
            // contains the substring `q`, add it to the `matches` array
            $.each(strs, function(i, str) {
              if (substrRegex.test(str)) {
                matches.push(str);
              }
            });
        
            cb(matches);
          };
        };
        
        $('.selectize').select2();
        
        /*
        companies = [$unique_companies];
        countries =[$unique_countries]
        
        $('#company-ahead').typeahead({
          hint: true,
          highlight: true,
          minLength: 1
        },
        {
          name: 'company',
          source: substringMatcher(companies)
        });
        
        $('#country-ahead').typeahead({
        
          hint: true,
          highlight: true,
          minLength: 1
        },
        {
          name: 'country',
          source: substringMatcher(countries)
        });
      
        $(document).on('pjax:success', function() {
          $("html, body").animate({ scrollTop: 220 }, 1250);
        });
        
        $('#company-ahead').on('blur', function() {
          $('#filter').submit();
        });
        */
      });
JS;

    \Yii::$app->controller->view->registerJs($js);

    return $out;
  }

  private function buildSelfArray($data)
  {
    $selfArray = [];

    foreach ($data as $item) {
      $selfArray[$item] = $item;
    }

    $selfArray = array_merge(['0' => 'Alle'], $selfArray);

    return $selfArray;
  }
}

